### PR TITLE
Multiple export as default

### PR DESCRIPTION
**Pull request by aminya**
https://github.com/59naga/babel-plugin-add-module-exports/pull/82#issue-329834685

### CODE REVIEW

**Comment by aminya** [comment]
@lijunle Any plan to merge these? These are critical to us in Atom community (https://github.com/atom-ide-community/atom/pull/67#issuecomment-688536441). If you can't maintain this repository anymore, we have an active fork here: 
https://github.com/atom-ide-community/babel-plugin-add-module-exports

We would appreciate it if you can give us access to release the patches under the original name.

I have planned a couple of patches myself which totally removes the issues:
https://github.com/atom-ide-community/babel-plugin-add-module-exports/pull/4

**Comment by lijunle** [comment]
@aminya I am not actively working on this project any more. It is great that you and the community can continue the maintenance of this package. I am totally ok to add you as the owner then you can push the release from your fork. 

Try to connect @59naga and @ljharb to see if they have any concerns. If they don’t have further concerns within 1 day, I will update the permissions.

**Comment by ljharb** [comment]
I'll be happy to review, merge, and release the PR; I'd deferred while I thought @lijunle was still maintaining.

@lijunle if you're not interested in maintaining it further, i'd be happy to accept a repo transfer, so i can administer CI checks.

**Comment by ljharb** [comment]
@aminya i'd love to rebase this PR, but i don't have access to your atom-ide-community fork. Can you add me?

**Comment by lijunle** [comment]
@ljharb my repo is just a fork with 1 more fix ahead of @52naga ‘s original repo. 

> https://github.com/59naga/babel-plugin-add-module-exports/compare/master...lijunle:master

I don’t have permission to access @52naga ‘s original repo. My idea is, set up a new repo for this plugin (maybe use atom-ide-community fork), then update the package.json and publish new version to point to the new repo. Both you and I have the access to publish the new versions to npm.

**Comment by ljharb** [comment]
@lijunle sure, but this one has issues and PRs, and it'd be nice to preserve that rather than littering github with multiple forks that don't redirect to each other :-)

**Comment by aminya** [comment]
>  I am totally ok to add you as the owner then you can push the release from your fork.

@lijunle That would be awesome. I'm happy to continue fixing the edge cases of this software. We have a tone of mixed ES5/ES6 packages that we can't convert to ES6.

> @aminya i'd love to rebase this PR, but i don't have access to your atom-ide-community fork. Can you add me?

@ljharb I sent you an invitation. This branch is already rebased, and it is also on the master of my fork. 

> it'd be nice to preserve that rather than littering github with multiple forks that don't redirect to each other :-)

Both works for me. I'd prefer to transfer the repository to the organization, so everyone can contribute to.

**Comment by ljharb** [comment]
I'd be happy to make an org for it.

**Comment by ljharb** [comment]
@aminya i joined, but don't seem to be on the repo yet. (it's not rebased yet because there's a merge commit in it)

**Comment by aminya** [comment]
> @aminya i joined, but don't seem to be on the repo yet.

I gave you proper access. Let's wait until we decide about the way to go. Maybe we need to remove that repo.

>  (it's not rebased yet because there's a merge commit in it)

That's fine to me. I don't mind about the merge commit.

**Review by ljharb — APPROVED** [review]

**Pull request merged**
